
import java.awt.event.MouseEvent;
import javax.swing.JMenuItem;


public class Home extends javax.swing.JFrame{

    public Home() {
        initComponents();
        setLocationRelativeTo(null);   
    }
    private void showPopUp(MouseEvent e){
        popMenu.show(this, e.getX(), e.getY());
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popMenu = new javax.swing.JPopupMenu();
        popTrivia = new javax.swing.JMenu();
        trivPH = new javax.swing.JMenuItem();
        trivCS = new javax.swing.JMenuItem();
        popPong = new javax.swing.JMenuItem();
        popSnake = new javax.swing.JMenuItem();
        popExit = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        trivia = new javax.swing.JMenu();
        history = new javax.swing.JMenu();
        trivEasy = new javax.swing.JMenuItem();
        trivMedium = new javax.swing.JMenuItem();
        trivHard = new javax.swing.JMenuItem();
        computer = new javax.swing.JMenu();
        compEasy = new javax.swing.JMenuItem();
        compMedium = new javax.swing.JMenuItem();
        compHard = new javax.swing.JMenuItem();
        pong = new javax.swing.JMenu();
        pongEasy = new javax.swing.JMenuItem();
        pongMedium = new javax.swing.JMenuItem();
        pongHard = new javax.swing.JMenuItem();
        snake = new javax.swing.JMenu();
        utEasy = new javax.swing.JMenuItem();
        utMedium = new javax.swing.JMenuItem();
        utHard = new javax.swing.JMenuItem();
        exit = new javax.swing.JMenu();
        homeClose = new javax.swing.JMenuItem();

        popTrivia.setText("Trivia");

        trivPH.setText("Philippine History");
        trivPH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trivPHActionPerformed(evt);
            }
        });
        popTrivia.add(trivPH);

        trivCS.setText("Computer Science");
        trivCS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trivCSActionPerformed(evt);
            }
        });
        popTrivia.add(trivCS);

        popMenu.add(popTrivia);

        popPong.setText("Pong");
        popPong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popPongActionPerformed(evt);
            }
        });
        popMenu.add(popPong);

        popSnake.setText("Snake");
        popSnake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popSnakeActionPerformed(evt);
            }
        });
        popMenu.add(popSnake);

        popExit.setText("Exit");
        popExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popExitActionPerformed(evt);
            }
        });
        popMenu.add(popExit);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 51), 2, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Imprint MT Shadow", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Mapua Arcade");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 70));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 430, 70));

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51), 2));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Imprint MT Shadow", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("You want to play? Let's play!");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 60));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 520, 60));

        jPanel3.setBackground(new java.awt.Color(255, 204, 204));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 51), 2, true));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Snap ITC", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 51));
        jLabel6.setText("TRIVIA");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 170, 60));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 190, 60));

        jPanel4.setBackground(new java.awt.Color(255, 204, 204));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 51), 2, true));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Bauhaus 93", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 51));
        jLabel7.setText("PONG");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 100, 60));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 290, 120, 60));

        jPanel5.setBackground(new java.awt.Color(255, 204, 204));
        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 51), 2, true));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Power Green", 1, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 51));
        jLabel8.setText("SNAKE");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 130, 50));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, 160, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel1MouseReleased(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, -1));

        trivia.setMnemonic('t');
        trivia.setText("Trivia");

        history.setText("Philippine History");

        trivEasy.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        trivEasy.setText("Easy");
        trivEasy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trivEasyActionPerformed(evt);
            }
        });
        history.add(trivEasy);

        trivMedium.setText("Medium");
        trivMedium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trivMediumActionPerformed(evt);
            }
        });
        history.add(trivMedium);

        trivHard.setText("Hard");
        trivHard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trivHardActionPerformed(evt);
            }
        });
        history.add(trivHard);

        trivia.add(history);

        computer.setText("Computer Science");

        compEasy.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.SHIFT_MASK));
        compEasy.setText("Easy");
        compEasy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compEasyActionPerformed(evt);
            }
        });
        computer.add(compEasy);

        compMedium.setText("Medium");
        compMedium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compMediumActionPerformed(evt);
            }
        });
        computer.add(compMedium);

        compHard.setText("Hard");
        compHard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compHardActionPerformed(evt);
            }
        });
        computer.add(compHard);

        trivia.add(computer);

        jMenuBar1.add(trivia);

        pong.setMnemonic('p');
        pong.setText("Pong");

        pongEasy.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        pongEasy.setText("Easy");
        pongEasy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pongEasyActionPerformed(evt);
            }
        });
        pong.add(pongEasy);

        pongMedium.setText("Medium");
        pongMedium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pongMediumActionPerformed(evt);
            }
        });
        pong.add(pongMedium);

        pongHard.setText("Hard");
        pongHard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pongHardActionPerformed(evt);
            }
        });
        pong.add(pongHard);

        jMenuBar1.add(pong);

        snake.setMnemonic('s');
        snake.setText("Snake");

        utEasy.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        utEasy.setText("Easy");
        utEasy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                utEasyActionPerformed(evt);
            }
        });
        snake.add(utEasy);

        utMedium.setText("Medium");
        utMedium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                utMediumActionPerformed(evt);
            }
        });
        snake.add(utMedium);

        utHard.setText("Hard");
        utHard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                utHardActionPerformed(evt);
            }
        });
        snake.add(utHard);

        jMenuBar1.add(snake);

        exit.setMnemonic('e');
        exit.setText("Exit");

        homeClose.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        homeClose.setText("Exit Arcade");
        homeClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeCloseActionPerformed(evt);
            }
        });
        exit.add(homeClose);

        jMenuBar1.add(exit);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void trivEasyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trivEasyActionPerformed
        Trivia trivia = new Trivia();
        trivia.show();
        
        dispose();
    }//GEN-LAST:event_trivEasyActionPerformed

    private void trivMediumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trivMediumActionPerformed
        Trivia2 trivia2 = new Trivia2();
        trivia2.show();
        
        dispose();
    }//GEN-LAST:event_trivMediumActionPerformed

    private void trivHardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trivHardActionPerformed
        Trivia3 trivia3 = new Trivia3();
        trivia3.show();
        
        dispose();
    }//GEN-LAST:event_trivHardActionPerformed

    private void compEasyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compEasyActionPerformed
        Trivia4 trivia4 = new Trivia4();
        trivia4.show();
        
        dispose();
    }//GEN-LAST:event_compEasyActionPerformed

    private void compMediumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compMediumActionPerformed
        Trivia5 trivia5 = new Trivia5();
        trivia5.show();
        
        dispose();
    }//GEN-LAST:event_compMediumActionPerformed

    private void compHardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compHardActionPerformed
        Trivia6 trivia6 = new Trivia6();
        trivia6.show();
        
        dispose();
    }//GEN-LAST:event_compHardActionPerformed

    private void utEasyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_utEasyActionPerformed
       GamePanel.DELAY = 100;
       new GameFrame();
    }//GEN-LAST:event_utEasyActionPerformed

    private void utMediumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_utMediumActionPerformed
       GamePanel.DELAY = 60;
       new GameFrame();
    }//GEN-LAST:event_utMediumActionPerformed

    private void utHardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_utHardActionPerformed
       GamePanel.DELAY = 20;
       new GameFrame();
    }//GEN-LAST:event_utHardActionPerformed

    private void pongEasyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pongEasyActionPerformed
        Ball.initialSpeed = 2;
        new GameFramePong();
    }//GEN-LAST:event_pongEasyActionPerformed

    private void pongMediumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pongMediumActionPerformed
        Ball.initialSpeed = 6;
        new GameFramePong();
    }//GEN-LAST:event_pongMediumActionPerformed

    private void pongHardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pongHardActionPerformed
        Ball.initialSpeed = 10;
        new GameFramePong();
    }//GEN-LAST:event_pongHardActionPerformed

    private void homeCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeCloseActionPerformed
        System.exit(0);
    }//GEN-LAST:event_homeCloseActionPerformed

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        if(evt.isPopupTrigger()){
            showPopUp(evt);
        }
    }//GEN-LAST:event_jLabel1MousePressed

    private void jLabel1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseReleased
        if(evt.isPopupTrigger()){
        showPopUp(evt);
        }
    }//GEN-LAST:event_jLabel1MouseReleased

    private void trivPHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trivPHActionPerformed
        Trivia trivia = new Trivia();
        trivia.show();
        
        dispose();
    }//GEN-LAST:event_trivPHActionPerformed

    private void trivCSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trivCSActionPerformed
        Trivia4 trivia4 = new Trivia4();
        trivia4.show();
        
        dispose();
    }//GEN-LAST:event_trivCSActionPerformed

    private void popPongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popPongActionPerformed
        Ball.initialSpeed = 2;
        new GameFramePong();
    }//GEN-LAST:event_popPongActionPerformed

    private void popSnakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popSnakeActionPerformed
        GamePanel.DELAY = 100;
        new GameFrame();
    }//GEN-LAST:event_popSnakeActionPerformed

    private void popExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_popExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem compEasy;
    private javax.swing.JMenuItem compHard;
    private javax.swing.JMenuItem compMedium;
    private javax.swing.JMenu computer;
    private javax.swing.JMenu exit;
    private javax.swing.JMenu history;
    private javax.swing.JMenuItem homeClose;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JMenu pong;
    private javax.swing.JMenuItem pongEasy;
    private javax.swing.JMenuItem pongHard;
    private javax.swing.JMenuItem pongMedium;
    private javax.swing.JMenuItem popExit;
    private javax.swing.JPopupMenu popMenu;
    private javax.swing.JMenuItem popPong;
    private javax.swing.JMenuItem popSnake;
    private javax.swing.JMenu popTrivia;
    private javax.swing.JMenu snake;
    private javax.swing.JMenuItem trivCS;
    private javax.swing.JMenuItem trivEasy;
    private javax.swing.JMenuItem trivHard;
    private javax.swing.JMenuItem trivMedium;
    private javax.swing.JMenuItem trivPH;
    private javax.swing.JMenu trivia;
    private javax.swing.JMenuItem utEasy;
    private javax.swing.JMenuItem utHard;
    private javax.swing.JMenuItem utMedium;
    // End of variables declaration//GEN-END:variables
}
