/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MyApp;

import MyLib.MySqlClass;
import MyLib.MySqlClass;
import MyLib.Product;
import MyLib.Product;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Mark
 */
public class ReplenishForm extends javax.swing.JFrame {

    private MySqlClass mySql=new MySqlClass();
    private ArrayList<Product> prods;
    DefaultTableModel model1, model2;
    private static final DecimalFormat df = new DecimalFormat("0.00");
    int oldProdid, prodid, quantity;;
    public ReplenishForm() {
        initComponents();
        setLocationRelativeTo(null); 
    }
    Connection con;
    PreparedStatement pst;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ReplenishTable = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ExpiredTable = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        removeprod = new javax.swing.JButton();
        idtxt2 = new javax.swing.JTextField();
        nametxt2 = new javax.swing.JTextField();
        qtytxt2 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        refresh2 = new javax.swing.JButton();
        removalReport = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        updateqty = new javax.swing.JButton();
        idtxt = new javax.swing.JTextField();
        nametxt = new javax.swing.JTextField();
        qtytxt = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        refresh1 = new javax.swing.JButton();
        replenishReport = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        backHome = new javax.swing.JMenuItem();
        option = new javax.swing.JMenu();
        menu1 = new javax.swing.JMenuItem();
        menu2 = new javax.swing.JMenuItem();
        menu3 = new javax.swing.JMenuItem();
        genRep = new javax.swing.JMenu();
        rep1 = new javax.swing.JMenuItem();
        rep2 = new javax.swing.JMenuItem();
        rep3 = new javax.swing.JMenuItem();
        rep4 = new javax.swing.JMenuItem();
        refresh = new javax.swing.JMenuItem();
        logout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1436, 862));
        setPreferredSize(new java.awt.Dimension(1436, 862));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 153, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5), "Products to be Replenished", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        ReplenishTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Status", "Acquisition Price", "Quantity"
            }
        ));
        ReplenishTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReplenishTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ReplenishTable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 932, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 970, 310));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5), "Products to be Removed", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        ExpiredTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Status", "Quantity", "Expiry Date"
            }
        ));
        ExpiredTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExpiredTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(ExpiredTable);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 932, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 970, 320));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5), "Remove Products", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("Quantity:");
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText("ID:");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setText("Name:");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        removeprod.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        removeprod.setText("Remove");
        removeprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeprodActionPerformed(evt);
            }
        });
        jPanel5.add(removeprod, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 170, -1));

        idtxt2.setEditable(false);
        idtxt2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel5.add(idtxt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 170, -1));

        nametxt2.setEditable(false);
        nametxt2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel5.add(nametxt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 170, -1));

        qtytxt2.setEditable(false);
        qtytxt2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel5.add(qtytxt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 170, -1));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5), "Replenish Products", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setText("Quantity:");
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel6.setText("ID:");
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel7.setText("Name:");
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButton2.setText("Add");
        jPanel6.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 170, -1));

        jTextField4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel6.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 170, -1));

        jTextField5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel6.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 170, -1));

        jTextField6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel6.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 170, -1));

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 550, 330, 220));

        refresh2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        refresh2.setText("Reset");
        refresh2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refresh2ActionPerformed(evt);
            }
        });
        jPanel5.add(refresh2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 170, -1));

        removalReport.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        removalReport.setText("Generate Report");
        removalReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removalReportActionPerformed(evt);
            }
        });
        jPanel5.add(removalReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 170, -1));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 460, 370, 320));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5), "Replenish Products", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel8.setText("Quantity:");
        jPanel7.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel9.setText("ID:");
        jPanel7.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel10.setText("Name:");
        jPanel7.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        updateqty.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        updateqty.setText("Replenish");
        updateqty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateqtyActionPerformed(evt);
            }
        });
        jPanel7.add(updateqty, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 170, -1));

        idtxt.setEditable(false);
        idtxt.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel7.add(idtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 170, -1));

        nametxt.setEditable(false);
        nametxt.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel7.add(nametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 170, -1));

        qtytxt.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel7.add(qtytxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 170, -1));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5), "Replenish Products", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel11.setText("Quantity:");
        jPanel8.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel12.setText("ID:");
        jPanel8.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel13.setText("Name:");
        jPanel8.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButton4.setText("Add");
        jPanel8.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 170, -1));

        jTextField10.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel8.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 170, -1));

        jTextField11.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel8.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 170, -1));

        jTextField12.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel8.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 170, -1));

        jPanel7.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 550, 330, 220));

        refresh1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        refresh1.setText("Reset");
        refresh1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refresh1ActionPerformed(evt);
            }
        });
        jPanel7.add(refresh1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 170, -1));

        replenishReport.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        replenishReport.setText("Generate Report");
        replenishReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                replenishReportActionPerformed(evt);
            }
        });
        jPanel7.add(replenishReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 260, 170, -1));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 130, 370, 310));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 1, 57)); // NOI18N
        jLabel1.setText("Information and Inventory Management System ");

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyApp/logo2.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 1380, 100));

        jMenu1.setText("File");

        backHome.setText("Home");
        backHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backHomeActionPerformed(evt);
            }
        });
        jMenu1.add(backHome);

        option.setText("Options");

        menu1.setText("Home");
        menu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu1ActionPerformed(evt);
            }
        });
        option.add(menu1);

        menu2.setText("Manage Inventory");
        menu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu2ActionPerformed(evt);
            }
        });
        option.add(menu2);

        menu3.setText("Sell Inventory");
        menu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu3ActionPerformed(evt);
            }
        });
        option.add(menu3);

        genRep.setText("Generate Report");

        rep1.setText("Product Record Report");
        rep1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rep1ActionPerformed(evt);
            }
        });
        genRep.add(rep1);

        rep2.setText("Product Replenishing Report");
        rep2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rep2ActionPerformed(evt);
            }
        });
        genRep.add(rep2);

        rep3.setText("Product Removal Report");
        rep3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rep3ActionPerformed(evt);
            }
        });
        genRep.add(rep3);

        rep4.setText("Sold Products Report");
        rep4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rep4ActionPerformed(evt);
            }
        });
        genRep.add(rep4);

        option.add(genRep);

        jMenu1.add(option);

        refresh.setText("Refresh Page");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });
        jMenu1.add(refresh);

        logout.setText("Log Out");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jMenu1.add(logout);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1430, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 811, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        showRepTable();
        showExpTable();
           
    }//GEN-LAST:event_formWindowOpened

    private void menu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu1ActionPerformed
        Home home = new Home();
        home.show();
        dispose();
    }//GEN-LAST:event_menu1ActionPerformed

    private void menu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu2ActionPerformed
        InventoryForm ivform = new InventoryForm();
        ivform.show();
        dispose();
    }//GEN-LAST:event_menu2ActionPerformed

    private void menu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu3ActionPerformed
        SellForm sellform = new SellForm();
        sellform.show();        
        dispose();
    }//GEN-LAST:event_menu3ActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        ReplenishForm buyform = new ReplenishForm();
        buyform.show();
        dispose();
    }//GEN-LAST:event_refreshActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        LoginForm login = new LoginForm();
        login.show();
        dispose();
    }//GEN-LAST:event_logoutActionPerformed

    private void ReplenishTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReplenishTableMouseClicked
       DefaultTableModel model = (DefaultTableModel)ReplenishTable.getModel();

       int selectedRowIndex = ReplenishTable.getSelectedRow();
       
       idtxt.setText(model.getValueAt(selectedRowIndex, 0).toString());
       nametxt.setText(model.getValueAt(selectedRowIndex, 1).toString());
       qtytxt.setText(model.getValueAt(selectedRowIndex, 4).toString());
    }//GEN-LAST:event_ReplenishTableMouseClicked

    private void ExpiredTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExpiredTableMouseClicked
       DefaultTableModel model = (DefaultTableModel)ExpiredTable.getModel();

       int selectedRowIndex = ExpiredTable.getSelectedRow();
       
       idtxt2.setText(model.getValueAt(selectedRowIndex, 0).toString());
       nametxt2.setText(model.getValueAt(selectedRowIndex, 1).toString());
       qtytxt2.setText(model.getValueAt(selectedRowIndex, 3).toString());
    }//GEN-LAST:event_ExpiredTableMouseClicked

    private void refresh1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refresh1ActionPerformed
        showRepTable();
        showExpTable();
        resetAll();
    }//GEN-LAST:event_refresh1ActionPerformed

    private void refresh2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refresh2ActionPerformed
        showRepTable();
        showExpTable();
        resetAll();
    }//GEN-LAST:event_refresh2ActionPerformed

    private void updateqtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateqtyActionPerformed
        //replenishes product quantity and updates database
        if(idtxt.getText().isEmpty()||nametxt.getText().isEmpty()||qtytxt.getText().isEmpty())
            JOptionPane.showMessageDialog(null,"Please check that all inputs are filled!");
        else{
        DefaultTableModel model = (DefaultTableModel)ReplenishTable.getModel();

        int selectedRowIndex = ReplenishTable.getSelectedRow();
        prodid = Integer.parseInt((model.getValueAt(selectedRowIndex, 0).toString()));
        quantity = Integer.parseInt(qtytxt.getText()) + Integer.parseInt((model.getValueAt(selectedRowIndex, 4).toString()));
        
        mySql.updateQty(prodid, quantity);  //updates record quantity in database based on input
        showRepTable();
        resetAll();
        }
    }//GEN-LAST:event_updateqtyActionPerformed

    private void removeprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeprodActionPerformed
       //removes a product from database
        if(idtxt2.getText().isEmpty()||nametxt2.getText().isEmpty()||qtytxt2.getText().isEmpty())
            JOptionPane.showMessageDialog(null,"Please check that all inputs are filled!");
        else{
        DefaultTableModel model = (DefaultTableModel)ExpiredTable.getModel();

        int selectedRowIndex = ExpiredTable.getSelectedRow();
        prodid = Integer.parseInt((model.getValueAt(selectedRowIndex, 0).toString()));
        
        mySql.deleteExp(prodid);  //deletes a record of an expired product from database
        showExpTable();
        resetAll();
        }
    }//GEN-LAST:event_removeprodActionPerformed

    private void replenishReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_replenishReportActionPerformed
        //generate report for all products that need replenishing
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            try {
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/agrikulturadb?zeroDateTimeBehavior=convertToNull","root","jeet"); //connects to database
                try {
                    JasperDesign jdesign = JRXmlLoader.load("C:\\Users\\janed\\Documents\\NetBeansProjects\\agrikulturadb\\src\\MyApp\\ReplenishReport.jrxml");
                    String query = "select PRODID, PRODNAME, PRODSTATUS, PRODACQPRC, PRODQUANTITY from prodrec where PRODQUANTITY < 10 AND PRODSTATUS = 'Good'"; //gets all records where product is good and quantity is below 0
                
                    JRDesignQuery updateQuery = new JRDesignQuery();
                    updateQuery.setText(query);
                
                    jdesign.setQuery(updateQuery);
                    JasperReport jreport = JasperCompileManager.compileReport(jdesign);
                    JasperPrint jprint = JasperFillManager.fillReport(jreport, null, con);  //fills report with data
                    
                    JasperViewer.viewReport(jprint);
                } catch (JRException ex) {
                    Logger.getLogger(InventoryForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            } catch (SQLException ex) {
                Logger.getLogger(InventoryForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(InventoryForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_replenishReportActionPerformed

    private void removalReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removalReportActionPerformed
        //generate rport for all products that are expired and need to be removed
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            try {
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/agrikulturadb?zeroDateTimeBehavior=convertToNull","root","jeet"); //connects to database
                try {
                    JasperDesign jdesign = JRXmlLoader.load("C:\\Users\\janed\\Documents\\NetBeansProjects\\agrikulturadb\\src\\MyApp\\RemoveReport.jrxml");
                    String query = "select PRODID, PRODNAME, PRODSTATUS, PRODSTATUS, PRODQUANTITY, EXPDATE from prodrec where PRODSTATUS = 'Expired'"; //gets all records where product is expired
                
                    JRDesignQuery updateQuery = new JRDesignQuery();
                    updateQuery.setText(query);
                
                    jdesign.setQuery(updateQuery);
                    JasperReport jreport = JasperCompileManager.compileReport(jdesign);
                    JasperPrint jprint = JasperFillManager.fillReport(jreport, null, con);  //fills report with data
                    
                    JasperViewer.viewReport(jprint);
                } catch (JRException ex) {
                    Logger.getLogger(InventoryForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            } catch (SQLException ex) {
                Logger.getLogger(InventoryForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(InventoryForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_removalReportActionPerformed

    private void rep1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rep1ActionPerformed
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            try {
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/agrikulturadb?zeroDateTimeBehavior=convertToNull","root","jeet");
                try {
                    JasperDesign jdesign = JRXmlLoader.load("C:\\Users\\janed\\Documents\\NetBeansProjects\\agrikulturadb\\src\\MyApp\\ProductReport.jrxml");
                    String query = "select * from prodrec";
                
                    JRDesignQuery updateQuery = new JRDesignQuery();
                    updateQuery.setText(query);
                
                    jdesign.setQuery(updateQuery);
                    JasperReport jreport = JasperCompileManager.compileReport(jdesign);
                    JasperPrint jprint = JasperFillManager.fillReport(jreport, null, con);
                    
                    JasperViewer.viewReport(jprint);
                } catch (JRException ex) {
                    Logger.getLogger(InventoryForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            } catch (SQLException ex) {
                Logger.getLogger(InventoryForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(InventoryForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_rep1ActionPerformed

    private void rep2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rep2ActionPerformed
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            try {
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/agrikulturadb?zeroDateTimeBehavior=convertToNull","root","jeet");
                try {
                    JasperDesign jdesign = JRXmlLoader.load("C:\\Users\\janed\\Documents\\NetBeansProjects\\agrikulturadb\\src\\MyApp\\ReplenishReport.jrxml");
                    String query = "select PRODID, PRODNAME, PRODSTATUS, PRODACQPRC, PRODQUANTITY from prodrec where PRODQUANTITY < 10 AND PRODSTATUS = 'Good'";
                
                    JRDesignQuery updateQuery = new JRDesignQuery();
                    updateQuery.setText(query);
                
                    jdesign.setQuery(updateQuery);
                    JasperReport jreport = JasperCompileManager.compileReport(jdesign);
                    JasperPrint jprint = JasperFillManager.fillReport(jreport, null, con);
                    
                    JasperViewer.viewReport(jprint);
                } catch (JRException ex) {
                    Logger.getLogger(InventoryForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            } catch (SQLException ex) {
                Logger.getLogger(InventoryForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(InventoryForm.class.getName()).log(Level.SEVERE, null, ex);
        }   
    }//GEN-LAST:event_rep2ActionPerformed

    private void rep3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rep3ActionPerformed
            try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            try {
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/agrikulturadb?zeroDateTimeBehavior=convertToNull","root","jeet");
                try {
                    JasperDesign jdesign = JRXmlLoader.load("C:\\Users\\janed\\Documents\\NetBeansProjects\\agrikulturadb\\src\\MyApp\\RemoveReport.jrxml");
                    String query = "select PRODID, PRODNAME, PRODSTATUS, PRODSTATUS, PRODQUANTITY, EXPDATE from prodrec where PRODSTATUS = 'Expired'";
                
                    JRDesignQuery updateQuery = new JRDesignQuery();
                    updateQuery.setText(query);
                
                    jdesign.setQuery(updateQuery);
                    JasperReport jreport = JasperCompileManager.compileReport(jdesign);
                    JasperPrint jprint = JasperFillManager.fillReport(jreport, null, con);
                    
                    JasperViewer.viewReport(jprint);
                } catch (JRException ex) {
                    Logger.getLogger(InventoryForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            } catch (SQLException ex) {
                Logger.getLogger(InventoryForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(InventoryForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_rep3ActionPerformed

    private void rep4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rep4ActionPerformed
            try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            try {
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/agrikulturadb?zeroDateTimeBehavior=convertToNull","root","jeet");
                try {
                    JasperDesign jdesign = JRXmlLoader.load("C:\\Users\\janed\\Documents\\NetBeansProjects\\agrikulturadb\\src\\MyApp\\SoldProductReport.jrxml");
                    String query = "select * from sellrec";
                
                    JRDesignQuery updateQuery = new JRDesignQuery();
                    updateQuery.setText(query);
                
                    jdesign.setQuery(updateQuery);
                    JasperReport jreport = JasperCompileManager.compileReport(jdesign);
                    JasperPrint jprint = JasperFillManager.fillReport(jreport, null, con);
                    
                    JasperViewer.viewReport(jprint);
                } catch (JRException ex) {
                    Logger.getLogger(InventoryForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            } catch (SQLException ex) {
                Logger.getLogger(InventoryForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(InventoryForm.class.getName()).log(Level.SEVERE, null, ex);
        }        
    }//GEN-LAST:event_rep4ActionPerformed

    private void backHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backHomeActionPerformed
        Home home = new Home();
        home.show();
        dispose();
    }//GEN-LAST:event_backHomeActionPerformed
    
    public void clearReplenishTable()  //clears contents of replenish table
    {
        model1=(DefaultTableModel) ReplenishTable.getModel();
        model1.getDataVector().removeAllElements();
        model1.fireTableDataChanged();
    }
    
    public void clearExpiredTable() //clears contents of expired table
    {
        model2=(DefaultTableModel) ExpiredTable.getModel();
        model2.getDataVector().removeAllElements();
        model2.fireTableDataChanged();
    }
    
    public void showRepTable()      //shows data in rep table
    {
        clearReplenishTable();
        prods = mySql.displayRec();
        model1=(DefaultTableModel) ReplenishTable.getModel();
        for(Product p: prods)
           if(p.getQuantity() < 10 && "Good".equals(p.getStatus()))
               model1.addRow(new Object[] {p.getProdid(),p.getName(),p.getStatus(),df.format(p.getAcqprc()),p.getQuantity()});
    }
    
    public void showExpTable()      //shows data in exp table
    {       
        clearExpiredTable();
        prods = mySql.displayRec();
        model2=(DefaultTableModel) ExpiredTable.getModel();
        for(Product p: prods)
           if("Expired".equals(p.getStatus()))
               model2.addRow(new Object[] {p.getProdid(),p.getName(),p.getStatus(),p.getQuantity(),p.getExpdate()});
    }
    
    public void resetAll()      //resets input fields
    {
        idtxt.setText("");
        nametxt.setText("");
        qtytxt.setText("");
        idtxt2.setText("");
        nametxt2.setText("");
        qtytxt2.setText("");       
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReplenishForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReplenishForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReplenishForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReplenishForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReplenishForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ExpiredTable;
    private javax.swing.JTable ReplenishTable;
    private javax.swing.JMenuItem backHome;
    private javax.swing.JMenu genRep;
    private javax.swing.JTextField idtxt;
    private javax.swing.JTextField idtxt2;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JMenuItem logout;
    private javax.swing.JMenuItem menu1;
    private javax.swing.JMenuItem menu2;
    private javax.swing.JMenuItem menu3;
    private javax.swing.JTextField nametxt;
    private javax.swing.JTextField nametxt2;
    private javax.swing.JMenu option;
    private javax.swing.JTextField qtytxt;
    private javax.swing.JTextField qtytxt2;
    private javax.swing.JMenuItem refresh;
    private javax.swing.JButton refresh1;
    private javax.swing.JButton refresh2;
    private javax.swing.JButton removalReport;
    private javax.swing.JButton removeprod;
    private javax.swing.JMenuItem rep1;
    private javax.swing.JMenuItem rep2;
    private javax.swing.JMenuItem rep3;
    private javax.swing.JMenuItem rep4;
    private javax.swing.JButton replenishReport;
    private javax.swing.JButton updateqty;
    // End of variables declaration//GEN-END:variables
}
