/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MyApp;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author janed
 */
public class ReportForm extends javax.swing.JFrame {

    /**
     * Creates new form LoginForm
     */
    public ReportForm() {
        initComponents();
        setLocationRelativeTo(null); 
        showDate();
        showTime();
    }
    Connection con;
    PreparedStatement pst;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        report1 = new javax.swing.JButton();
        report2 = new javax.swing.JButton();
        report3 = new javax.swing.JButton();
        report4 = new javax.swing.JButton();
        time = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        backHome = new javax.swing.JMenuItem();
        option = new javax.swing.JMenu();
        menuhome = new javax.swing.JMenuItem();
        menu1 = new javax.swing.JMenuItem();
        menu2 = new javax.swing.JMenuItem();
        menu3 = new javax.swing.JMenuItem();
        genRep = new javax.swing.JMenu();
        rep1 = new javax.swing.JMenuItem();
        rep2 = new javax.swing.JMenuItem();
        rep3 = new javax.swing.JMenuItem();
        rep4 = new javax.swing.JMenuItem();
        refresh = new javax.swing.JMenuItem();
        logout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1446, 829));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 153, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 153, 102));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyApp/logo.jpg"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, 190));

        jLabel2.setFont(new java.awt.Font("Monotype Corsiva", 1, 30)); // NOI18N
        jLabel2.setText("Information and Inventory Management System");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Welcome! Which report would you like to be generated?");

        report1.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        report1.setText("Product Record Report");
        report1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                report1ActionPerformed(evt);
            }
        });

        report2.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        report2.setText("Product Repleneshing Report");
        report2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                report2ActionPerformed(evt);
            }
        });

        report3.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        report3.setText("Product Removal Report");
        report3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                report3ActionPerformed(evt);
            }
        });

        report4.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        report4.setText("Sold Products Report");
        report4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                report4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(372, 372, 372)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(report1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(report2, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(report3, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(report4, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(398, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(report1)
                .addGap(23, 23, 23)
                .addComponent(report2)
                .addGap(23, 23, 23)
                .addComponent(report3)
                .addGap(23, 23, 23)
                .addComponent(report4)
                .addContainerGap(115, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1430, 740));

        time.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        time.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 20, 80, 20));

        date.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        date.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 20, 70, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Admin");
        jLabel3.setToolTipText("");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1360, 20, -1, 20));

        jMenu1.setText("File");

        backHome.setText("Home");
        backHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backHomeActionPerformed(evt);
            }
        });
        jMenu1.add(backHome);

        option.setText("Options");

        menuhome.setText("Home");
        menuhome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuhomeActionPerformed(evt);
            }
        });
        option.add(menuhome);

        menu1.setText("Manage Inventory");
        menu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu1ActionPerformed(evt);
            }
        });
        option.add(menu1);

        menu2.setText("Replenish & Remove Inventory");
        menu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu2ActionPerformed(evt);
            }
        });
        option.add(menu2);

        menu3.setText("Sell Inventory");
        menu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu3ActionPerformed(evt);
            }
        });
        option.add(menu3);

        genRep.setText("Generate Report");

        rep1.setText("Product Record Report");
        rep1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rep1ActionPerformed(evt);
            }
        });
        genRep.add(rep1);

        rep2.setText("Product Replenishing Report");
        rep2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rep2ActionPerformed(evt);
            }
        });
        genRep.add(rep2);

        rep3.setText("Product Removal Report");
        rep3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rep3ActionPerformed(evt);
            }
        });
        genRep.add(rep3);

        rep4.setText("Sold Products Report");
        rep4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rep4ActionPerformed(evt);
            }
        });
        genRep.add(rep4);

        option.add(genRep);

        jMenu1.add(option);

        refresh.setText("Refresh Page");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });
        jMenu1.add(refresh);

        logout.setText("Log Out");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jMenu1.add(logout);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void report1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_report1ActionPerformed
        //generates inventory report
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            try {
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/agrikulturadb?zeroDateTimeBehavior=convertToNull","root","jeet"); //connects to database
                try {
                    JasperDesign jdesign = JRXmlLoader.load("C:\\Users\\janed\\Documents\\NetBeansProjects\\agrikulturadb\\src\\MyApp\\ProductReport.jrxml");
                    String query = "select * from prodrec"; //selects all records of products in inventory from the database
                
                    JRDesignQuery updateQuery = new JRDesignQuery();
                    updateQuery.setText(query);
                
                    jdesign.setQuery(updateQuery);
                    JasperReport jreport = JasperCompileManager.compileReport(jdesign);
                    JasperPrint jprint = JasperFillManager.fillReport(jreport, null, con);   //fills report with data
                    
                    JasperViewer.viewReport(jprint);
                } catch (JRException ex) {
                    Logger.getLogger(InventoryForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            } catch (SQLException ex) {
                Logger.getLogger(InventoryForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(InventoryForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_report1ActionPerformed

    private void report2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_report2ActionPerformed
        //generates product replenishing report
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            try {
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/agrikulturadb?zeroDateTimeBehavior=convertToNull","root","jeet"); //connects to database
                try {
                    JasperDesign jdesign = JRXmlLoader.load("C:\\Users\\janed\\Documents\\NetBeansProjects\\agrikulturadb\\src\\MyApp\\ReplenishReport.jrxml");
                    String query = "select PRODID, PRODNAME, PRODSTATUS, PRODACQPRC, PRODQUANTITY from prodrec where PRODQUANTITY < 10 AND PRODSTATUS = 'Good'"; //selects records where product is good and quantity is less than 10 
                
                    JRDesignQuery updateQuery = new JRDesignQuery();
                    updateQuery.setText(query);
                
                    jdesign.setQuery(updateQuery);
                    JasperReport jreport = JasperCompileManager.compileReport(jdesign);
                    JasperPrint jprint = JasperFillManager.fillReport(jreport, null, con);   //fills report with data
                    
                    JasperViewer.viewReport(jprint);
                } catch (JRException ex) {
                    Logger.getLogger(InventoryForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            } catch (SQLException ex) {
                Logger.getLogger(InventoryForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(InventoryForm.class.getName()).log(Level.SEVERE, null, ex);
        }   
    }//GEN-LAST:event_report2ActionPerformed

    private void report3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_report3ActionPerformed
        //generate expired products report    
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            try {
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/agrikulturadb?zeroDateTimeBehavior=convertToNull","root","jeet");  //connects to database
                try {
                    JasperDesign jdesign = JRXmlLoader.load("C:\\Users\\janed\\Documents\\NetBeansProjects\\agrikulturadb\\src\\MyApp\\RemoveReport.jrxml");
                    String query = "select PRODID, PRODNAME, PRODSTATUS, PRODSTATUS, PRODQUANTITY, EXPDATE from prodrec where PRODSTATUS = 'Expired'";  //selects records where product is expired
                 
                    JRDesignQuery updateQuery = new JRDesignQuery();
                    updateQuery.setText(query);
                
                    jdesign.setQuery(updateQuery);
                    JasperReport jreport = JasperCompileManager.compileReport(jdesign);
                    JasperPrint jprint = JasperFillManager.fillReport(jreport, null, con);  //fills report with data
                    
                    JasperViewer.viewReport(jprint);
                } catch (JRException ex) {
                    Logger.getLogger(InventoryForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            } catch (SQLException ex) {
                Logger.getLogger(InventoryForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(InventoryForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_report3ActionPerformed

    private void report4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_report4ActionPerformed
        //generates report of all sold products   
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            try {
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/agrikulturadb?zeroDateTimeBehavior=convertToNull","root","jeet");  //connects to database
                try {
                    JasperDesign jdesign = JRXmlLoader.load("C:\\Users\\janed\\Documents\\NetBeansProjects\\agrikulturadb\\src\\MyApp\\SoldProductReport.jrxml");  
                    String query = "select * from sellrec";  //selects all sold products from the database
                
                    JRDesignQuery updateQuery = new JRDesignQuery();
                    updateQuery.setText(query);
                
                    jdesign.setQuery(updateQuery);
                    JasperReport jreport = JasperCompileManager.compileReport(jdesign);
                    JasperPrint jprint = JasperFillManager.fillReport(jreport, null, con); //fills report with data
                    
                    JasperViewer.viewReport(jprint);
                } catch (JRException ex) {
                    Logger.getLogger(InventoryForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            } catch (SQLException ex) {
                Logger.getLogger(InventoryForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(InventoryForm.class.getName()).log(Level.SEVERE, null, ex);
        }        
    }//GEN-LAST:event_report4ActionPerformed

    private void menu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu1ActionPerformed
        InventoryForm ivform = new InventoryForm();
        ivform.show();
        dispose();
    }//GEN-LAST:event_menu1ActionPerformed

    private void menu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu2ActionPerformed
        ReplenishForm buyform = new ReplenishForm();
        buyform.show();       
        dispose();
    }//GEN-LAST:event_menu2ActionPerformed

    private void menu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu3ActionPerformed
        SellForm sellform = new SellForm();
        sellform.show();        
        dispose();
    }//GEN-LAST:event_menu3ActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        ReportForm home = new ReportForm();
        home.show();            
        dispose();
    }//GEN-LAST:event_refreshActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        JOptionPane.showMessageDialog(null,"Logging out!");
        LoginForm login = new LoginForm();
        login.show();       
        dispose();
    }//GEN-LAST:event_logoutActionPerformed

    private void rep1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rep1ActionPerformed
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            try {
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/agrikulturadb?zeroDateTimeBehavior=convertToNull","root","jeet");
                try {
                    JasperDesign jdesign = JRXmlLoader.load("C:\\Users\\janed\\Documents\\NetBeansProjects\\agrikulturadb\\src\\MyApp\\ProductReport.jrxml");
                    String query = "select * from prodrec";
                
                    JRDesignQuery updateQuery = new JRDesignQuery();
                    updateQuery.setText(query);
                
                    jdesign.setQuery(updateQuery);
                    JasperReport jreport = JasperCompileManager.compileReport(jdesign);
                    JasperPrint jprint = JasperFillManager.fillReport(jreport, null, con);
                    
                    JasperViewer.viewReport(jprint);
                } catch (JRException ex) {
                    Logger.getLogger(InventoryForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            } catch (SQLException ex) {
                Logger.getLogger(InventoryForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(InventoryForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_rep1ActionPerformed

    private void rep2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rep2ActionPerformed
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            try {
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/agrikulturadb?zeroDateTimeBehavior=convertToNull","root","jeet");
                try {
                    JasperDesign jdesign = JRXmlLoader.load("C:\\Users\\janed\\Documents\\NetBeansProjects\\agrikulturadb\\src\\MyApp\\ReplenishReport.jrxml");
                    String query = "select PRODID, PRODNAME, PRODSTATUS, PRODACQPRC, PRODQUANTITY from prodrec where PRODQUANTITY < 10 AND PRODSTATUS = 'Good'";
                
                    JRDesignQuery updateQuery = new JRDesignQuery();
                    updateQuery.setText(query);
                
                    jdesign.setQuery(updateQuery);
                    JasperReport jreport = JasperCompileManager.compileReport(jdesign);
                    JasperPrint jprint = JasperFillManager.fillReport(jreport, null, con);
                    
                    JasperViewer.viewReport(jprint);
                } catch (JRException ex) {
                    Logger.getLogger(InventoryForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            } catch (SQLException ex) {
                Logger.getLogger(InventoryForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(InventoryForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_rep2ActionPerformed

    private void rep3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rep3ActionPerformed
            try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            try {
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/agrikulturadb?zeroDateTimeBehavior=convertToNull","root","jeet");
                try {
                    JasperDesign jdesign = JRXmlLoader.load("C:\\Users\\janed\\Documents\\NetBeansProjects\\agrikulturadb\\src\\MyApp\\RemoveReport.jrxml");
                    String query = "select PRODID, PRODNAME, PRODSTATUS, PRODSTATUS, PRODQUANTITY, EXPDATE from prodrec where PRODSTATUS = 'Expired'";
                
                    JRDesignQuery updateQuery = new JRDesignQuery();
                    updateQuery.setText(query);
                
                    jdesign.setQuery(updateQuery);
                    JasperReport jreport = JasperCompileManager.compileReport(jdesign);
                    JasperPrint jprint = JasperFillManager.fillReport(jreport, null, con);
                    
                    JasperViewer.viewReport(jprint);
                } catch (JRException ex) {
                    Logger.getLogger(InventoryForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            } catch (SQLException ex) {
                Logger.getLogger(InventoryForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(InventoryForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_rep3ActionPerformed

    private void rep4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rep4ActionPerformed
            try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            try {
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/agrikulturadb?zeroDateTimeBehavior=convertToNull","root","jeet");
                try {
                    JasperDesign jdesign = JRXmlLoader.load("C:\\Users\\janed\\Documents\\NetBeansProjects\\agrikulturadb\\src\\MyApp\\SoldProductReport.jrxml");
                    String query = "select * from sellrec";
                
                    JRDesignQuery updateQuery = new JRDesignQuery();
                    updateQuery.setText(query);
                
                    jdesign.setQuery(updateQuery);
                    JasperReport jreport = JasperCompileManager.compileReport(jdesign);
                    JasperPrint jprint = JasperFillManager.fillReport(jreport, null, con);
                    
                    JasperViewer.viewReport(jprint);
                } catch (JRException ex) {
                    Logger.getLogger(InventoryForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            } catch (SQLException ex) {
                Logger.getLogger(InventoryForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(InventoryForm.class.getName()).log(Level.SEVERE, null, ex);
        }        
    }//GEN-LAST:event_rep4ActionPerformed

    private void backHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backHomeActionPerformed
        Home home = new Home();
        home.show();
        dispose();
    }//GEN-LAST:event_backHomeActionPerformed

    private void menuhomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuhomeActionPerformed
        Home home = new Home();
        home.show();
        dispose();
    }//GEN-LAST:event_menuhomeActionPerformed
    void showDate(){
            SimpleDateFormat s = new SimpleDateFormat("yyyy-MM-dd");
            Date d = new Date();
            date.setText(s.format(d));
    }  
    void showTime(){
        new Timer(0, new ActionListener(){
            
            @Override
            public void actionPerformed(ActionEvent e){
            SimpleDateFormat s = new SimpleDateFormat("hh:mm:ss a");
            Date d = new Date();
            time.setText(s.format(d));                   
            }  
        }).start();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReportForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReportForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReportForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReportForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReportForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem backHome;
    private javax.swing.JLabel date;
    private javax.swing.JMenu genRep;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JMenuItem logout;
    private javax.swing.JMenuItem menu1;
    private javax.swing.JMenuItem menu2;
    private javax.swing.JMenuItem menu3;
    private javax.swing.JMenuItem menuhome;
    private javax.swing.JMenu option;
    private javax.swing.JMenuItem refresh;
    private javax.swing.JMenuItem rep1;
    private javax.swing.JMenuItem rep2;
    private javax.swing.JMenuItem rep3;
    private javax.swing.JMenuItem rep4;
    private javax.swing.JButton report1;
    private javax.swing.JButton report2;
    private javax.swing.JButton report3;
    private javax.swing.JButton report4;
    private javax.swing.JLabel time;
    // End of variables declaration//GEN-END:variables
}
