/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MyApp;

import MyLib.MySqlClass;
import MyLib.Product;
import MyLib.SellProd;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Mark
 */
public class SellForm extends javax.swing.JFrame {

    private MySqlClass mySql=new MySqlClass();
    private static final DecimalFormat df = new DecimalFormat("0.00");
    private ArrayList<Product> prods;
    private ArrayList<SellProd> sellprods;
    DefaultTableModel model1, model2;
    int oldProdid, id, qty, qty2, qty3, id1;
    double total = 0, prc = 0,price;
    String name, qty1;
    int selectedRowIndex1;
    public SellForm() {
        initComponents();
        setLocationRelativeTo(null); 
    }
    Connection con;
    PreparedStatement pst;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cartTable = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        idtxt = new javax.swing.JTextField();
        qtytxt = new javax.swing.JTextField();
        process = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        totaltxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nametxt = new javax.swing.JTextField();
        prctxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Revert = new javax.swing.JButton();
        cashOut = new javax.swing.JButton();
        sellProdReport = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        availTable = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        backHome = new javax.swing.JMenuItem();
        option = new javax.swing.JMenu();
        menu1 = new javax.swing.JMenuItem();
        menu2 = new javax.swing.JMenuItem();
        menu3 = new javax.swing.JMenuItem();
        genRep = new javax.swing.JMenu();
        rep1 = new javax.swing.JMenuItem();
        rep2 = new javax.swing.JMenuItem();
        rep3 = new javax.swing.JMenuItem();
        rep4 = new javax.swing.JMenuItem();
        refresh = new javax.swing.JMenuItem();
        logout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1436, 862));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 153, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5), "Purchased", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        cartTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Selling Price", "Quantity"
            }
        ));
        cartTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cartTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(cartTable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1022, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 1060, 310));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5), "Add to Cart", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("AMOUNT DUE");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, -1, -1));

        idtxt.setEditable(false);
        idtxt.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel4.add(idtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 120, -1));

        qtytxt.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel4.add(qtytxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 120, -1));

        process.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        process.setText("Process");
        process.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processActionPerformed(evt);
            }
        });
        jPanel4.add(process, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 110, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setText("Product ID:");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        totaltxt.setEditable(false);
        totaltxt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel4.add(totaltxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, 130, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setText("Price:");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel6.setText("Name:");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        nametxt.setEditable(false);
        nametxt.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel4.add(nametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 120, -1));

        prctxt.setEditable(false);
        prctxt.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel4.add(prctxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 120, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel7.setText("Quantity:");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));
        jPanel4.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 270, -1));

        Revert.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Revert.setText("Revert");
        Revert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RevertActionPerformed(evt);
            }
        });
        jPanel4.add(Revert, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 110, -1));

        cashOut.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        cashOut.setText("Cash Out");
        cashOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashOutActionPerformed(evt);
            }
        });
        jPanel4.add(cashOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, 130, -1));

        sellProdReport.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        sellProdReport.setText("Generate Report");
        sellProdReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sellProdReportActionPerformed(evt);
            }
        });
        jPanel4.add(sellProdReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 460, 150, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 130, 300, 520));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 5), "Available Products", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        availTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Selling Price", "Quantity"
            }
        ));
        availTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                availTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(availTable);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1022, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 1060, 310));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 1, 57)); // NOI18N
        jLabel1.setText("Information and Inventory Management System ");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyApp/logo2.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 1380, 100));

        jMenu1.setText("File");

        backHome.setText("Home");
        backHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backHomeActionPerformed(evt);
            }
        });
        jMenu1.add(backHome);

        option.setText("Options");

        menu1.setText("Home");
        menu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu1ActionPerformed(evt);
            }
        });
        option.add(menu1);

        menu2.setText("Manage Inventory");
        menu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu2ActionPerformed(evt);
            }
        });
        option.add(menu2);

        menu3.setText("Replenish & Remove Inventory");
        menu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu3ActionPerformed(evt);
            }
        });
        option.add(menu3);

        genRep.setText("Generate Report");

        rep1.setText("Product Record Report");
        rep1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rep1ActionPerformed(evt);
            }
        });
        genRep.add(rep1);

        rep2.setText("Product Replenishing Report");
        rep2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rep2ActionPerformed(evt);
            }
        });
        genRep.add(rep2);

        rep3.setText("Product Removal Report");
        rep3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rep3ActionPerformed(evt);
            }
        });
        genRep.add(rep3);

        rep4.setText("Sold Products Report");
        rep4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rep4ActionPerformed(evt);
            }
        });
        genRep.add(rep4);

        option.add(genRep);

        jMenu1.add(option);

        refresh.setText("Refresh Page");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });
        jMenu1.add(refresh);

        logout.setText("Log Out");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jMenu1.add(logout);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1430, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 811, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        showAvailTable();

    }//GEN-LAST:event_formWindowOpened

    private void menu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu1ActionPerformed
        Home home = new Home();
        home.show();
        dispose();
    }//GEN-LAST:event_menu1ActionPerformed

    private void menu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu2ActionPerformed
        InventoryForm ivform = new InventoryForm();
        ivform.show();
        dispose();
    }//GEN-LAST:event_menu2ActionPerformed

    private void menu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu3ActionPerformed
        ReplenishForm buyform = new ReplenishForm();
        buyform.show();
        dispose();
    }//GEN-LAST:event_menu3ActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        SellForm sellform = new SellForm();
        sellform.show();        
        dispose();
    }//GEN-LAST:event_refreshActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        LoginForm login = new LoginForm();
        login.show();
        dispose();
    }//GEN-LAST:event_logoutActionPerformed

    private void availTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_availTableMouseClicked
       //show data of record clicked on the available products table in input fields
       DefaultTableModel model = (DefaultTableModel)availTable.getModel();

       int selectedRowIndex = availTable.getSelectedRow();
       
       idtxt.setText(model.getValueAt(selectedRowIndex, 0).toString());
       nametxt.setText(model.getValueAt(selectedRowIndex, 1).toString());
       prctxt.setText(model.getValueAt(selectedRowIndex, 2).toString());
       qtytxt.setText(model.getValueAt(selectedRowIndex, 3).toString());
       qty1 = model.getValueAt(selectedRowIndex, 3).toString();
    }//GEN-LAST:event_availTableMouseClicked

    private void processActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processActionPerformed
        //processes the products added to cart and to be sold
        if(idtxt.getText().isEmpty()||nametxt.getText().isEmpty()||qtytxt.getText().isEmpty()||prctxt.getText().isEmpty())
            JOptionPane.showMessageDialog(null,"Please check that all inputs are filled!");  //checks if all inputs are filled and appropriate
        else{
        model1=(DefaultTableModel) cartTable.getModel();
        model1.addRow(new Object[] {idtxt.getText(),nametxt.getText(),prctxt.getText(),qtytxt.getText()});
        prc = (Integer.parseInt(qtytxt.getText())) * (Double.parseDouble(prctxt.getText()));
        id = Integer.parseInt(idtxt.getText());
        name = nametxt.getText();
        price = Double.parseDouble(prctxt.getText());            
        qty = Integer.parseInt(qtytxt.getText());                   //gets data from input fields and updates quantity referring to how many products were sold
        total += prc;
        totaltxt.setText(Double.toString(total));
        mySql.createSellRec(id, name, qty, price);
        qty2 = Integer.parseInt(qty1) - qty;
        mySql.updateRec2(id, qty2);
        prc = 0;
        showAvailTable();
        resetAll();
        }
    }//GEN-LAST:event_processActionPerformed

    private void RevertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RevertActionPerformed
        //undos a product added to cart 
        if(idtxt.getText().isEmpty()||nametxt.getText().isEmpty()||qtytxt.getText().isEmpty()||prctxt.getText().isEmpty())
            JOptionPane.showMessageDialog(null,"Please check that all inputs are filled!");  //checks if all inputs are filled and appropriate
        else{
        id1 = Integer.parseInt(idtxt.getText());
        try {
            qty3 = mySql.reqQty(id1);    //gets quantity of selected product
        } catch (SQLException ex) {
            Logger.getLogger(SellForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        qty2 = Integer.parseInt(qtytxt.getText()) + qty3;

        mySql.deleteRec2(oldProdid);   //deletes record from database
        mySql.updateRec2(id1, qty2);   //updates record from database
        showAvailTable();
        prc = total - (Integer.parseInt(qtytxt.getText())) * (Double.parseDouble(prctxt.getText()));
        total = prc;
        totaltxt.setText(Double.toString(total));
        DefaultTableModel model = (DefaultTableModel)cartTable.getModel();

        selectedRowIndex1 = cartTable.getSelectedRow();
        model.removeRow(selectedRowIndex1);
        prc = 0;
        resetAll();
        }
    }//GEN-LAST:event_RevertActionPerformed

    private void cartTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cartTableMouseClicked
       //shows data in input fields of product selected from the table 
       DefaultTableModel model = (DefaultTableModel)cartTable.getModel();

       selectedRowIndex1 = cartTable.getSelectedRow();
       
       idtxt.setText(model.getValueAt(selectedRowIndex1, 0).toString());
       nametxt.setText(model.getValueAt(selectedRowIndex1, 1).toString());
       prctxt.setText(model.getValueAt(selectedRowIndex1, 2).toString());
       qtytxt.setText(model.getValueAt(selectedRowIndex1, 3).toString());
       qty1 = model.getValueAt(selectedRowIndex1, 3).toString();
    }//GEN-LAST:event_cartTableMouseClicked

    private void cashOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashOutActionPerformed
        //removes product in cart for cash out
        DefaultTableModel model = (DefaultTableModel)cartTable.getModel();
        
        int checker = model.getRowCount();
        if(checker == 0){
        JOptionPane.showMessageDialog(null,"Cart is Empty"); 
        }
        else{
        resetAll();
        clearcartTable();
        prc = 0;
        total = 0;
        totaltxt.setText("");
        JOptionPane.showMessageDialog(null,"Cash Out Successful!");
        }
    }//GEN-LAST:event_cashOutActionPerformed

    private void sellProdReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sellProdReportActionPerformed
        //generates report of sold products
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            try {
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/agrikulturadb?zeroDateTimeBehavior=convertToNull","root","jeet");  //connects to database
                try {
                    JasperDesign jdesign = JRXmlLoader.load("C:\\Users\\janed\\Documents\\NetBeansProjects\\agrikulturadb\\src\\MyApp\\SoldProductReport.jrxml");
                    String query = "select * from sellrec";  //selects all sold products from database
                
                    JRDesignQuery updateQuery = new JRDesignQuery();
                    updateQuery.setText(query);
                
                    jdesign.setQuery(updateQuery);
                    JasperReport jreport = JasperCompileManager.compileReport(jdesign);
                    JasperPrint jprint = JasperFillManager.fillReport(jreport, null, con);  //fills report with data
                    
                    JasperViewer.viewReport(jprint);
                } catch (JRException ex) {
                    Logger.getLogger(InventoryForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            } catch (SQLException ex) {
                Logger.getLogger(InventoryForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(InventoryForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_sellProdReportActionPerformed

    private void rep4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rep4ActionPerformed
            try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            try {
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/agrikulturadb?zeroDateTimeBehavior=convertToNull","root","jeet");
                try {
                    JasperDesign jdesign = JRXmlLoader.load("C:\\Users\\janed\\Documents\\NetBeansProjects\\agrikulturadb\\src\\MyApp\\SoldProductReport.jrxml");
                    String query = "select * from sellrec";
                
                    JRDesignQuery updateQuery = new JRDesignQuery();
                    updateQuery.setText(query);
                
                    jdesign.setQuery(updateQuery);
                    JasperReport jreport = JasperCompileManager.compileReport(jdesign);
                    JasperPrint jprint = JasperFillManager.fillReport(jreport, null, con);
                    
                    JasperViewer.viewReport(jprint);
                } catch (JRException ex) {
                    Logger.getLogger(InventoryForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            } catch (SQLException ex) {
                Logger.getLogger(InventoryForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(InventoryForm.class.getName()).log(Level.SEVERE, null, ex);
        }        
    }//GEN-LAST:event_rep4ActionPerformed

    private void rep1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rep1ActionPerformed
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            try {
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/agrikulturadb?zeroDateTimeBehavior=convertToNull","root","jeet");
                try {
                    JasperDesign jdesign = JRXmlLoader.load("C:\\Users\\janed\\Documents\\NetBeansProjects\\agrikulturadb\\src\\MyApp\\ProductReport.jrxml");
                    String query = "select * from prodrec";
                
                    JRDesignQuery updateQuery = new JRDesignQuery();
                    updateQuery.setText(query);
                
                    jdesign.setQuery(updateQuery);
                    JasperReport jreport = JasperCompileManager.compileReport(jdesign);
                    JasperPrint jprint = JasperFillManager.fillReport(jreport, null, con);
                    
                    JasperViewer.viewReport(jprint);
                } catch (JRException ex) {
                    Logger.getLogger(InventoryForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            } catch (SQLException ex) {
                Logger.getLogger(InventoryForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(InventoryForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_rep1ActionPerformed

    private void rep2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rep2ActionPerformed
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            try {
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/agrikulturadb?zeroDateTimeBehavior=convertToNull","root","jeet");
                try {
                    JasperDesign jdesign = JRXmlLoader.load("C:\\Users\\janed\\Documents\\NetBeansProjects\\agrikulturadb\\src\\MyApp\\ReplenishReport.jrxml");
                    String query = "select PRODID, PRODNAME, PRODSTATUS, PRODACQPRC, PRODQUANTITY from prodrec where PRODQUANTITY < 10 AND PRODSTATUS = 'Good'";
                
                    JRDesignQuery updateQuery = new JRDesignQuery();
                    updateQuery.setText(query);
                
                    jdesign.setQuery(updateQuery);
                    JasperReport jreport = JasperCompileManager.compileReport(jdesign);
                    JasperPrint jprint = JasperFillManager.fillReport(jreport, null, con);
                    
                    JasperViewer.viewReport(jprint);
                } catch (JRException ex) {
                    Logger.getLogger(InventoryForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            } catch (SQLException ex) {
                Logger.getLogger(InventoryForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(InventoryForm.class.getName()).log(Level.SEVERE, null, ex);
        }   
    }//GEN-LAST:event_rep2ActionPerformed

    private void rep3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rep3ActionPerformed
            try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            try {
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/agrikulturadb?zeroDateTimeBehavior=convertToNull","root","jeet");
                try {
                    JasperDesign jdesign = JRXmlLoader.load("C:\\Users\\janed\\Documents\\NetBeansProjects\\agrikulturadb\\src\\MyApp\\RemoveReport.jrxml");
                    String query = "select PRODID, PRODNAME, PRODSTATUS, PRODSTATUS, PRODQUANTITY, EXPDATE from prodrec where PRODSTATUS = 'Expired'";
                
                    JRDesignQuery updateQuery = new JRDesignQuery();
                    updateQuery.setText(query);
                
                    jdesign.setQuery(updateQuery);
                    JasperReport jreport = JasperCompileManager.compileReport(jdesign);
                    JasperPrint jprint = JasperFillManager.fillReport(jreport, null, con);
                    
                    JasperViewer.viewReport(jprint);
                } catch (JRException ex) {
                    Logger.getLogger(InventoryForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            } catch (SQLException ex) {
                Logger.getLogger(InventoryForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(InventoryForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_rep3ActionPerformed

    private void backHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backHomeActionPerformed
        Home home = new Home();
        home.show();
        dispose();
    }//GEN-LAST:event_backHomeActionPerformed
    
    public void clearavailTable()
    {
        model1=(DefaultTableModel) availTable.getModel();
        model1.getDataVector().removeAllElements();
        model1.fireTableDataChanged();
    }
    
    public void clearcartTable()
    {
        model2=(DefaultTableModel) cartTable.getModel();
        model2.getDataVector().removeAllElements();
        model2.fireTableDataChanged();
    }
  
    public void showAvailTable()
    {
        clearavailTable();
        prods = mySql.displayRec();
        model1=(DefaultTableModel) availTable.getModel();
        for(Product p: prods)
            if(p.getQuantity() > 0)
               model1.addRow(new Object[] {p.getProdid(),p.getName(),df.format(p.getSellprc()),p.getQuantity()});
    }
    
    public void resetAll()
    {
        idtxt.setText("");
        nametxt.setText("");
        prctxt.setText("");
        qtytxt.setText("");
    }

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SellForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SellForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SellForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SellForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SellForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Revert;
    private javax.swing.JTable availTable;
    private javax.swing.JMenuItem backHome;
    private javax.swing.JTable cartTable;
    private javax.swing.JButton cashOut;
    private javax.swing.JMenu genRep;
    private javax.swing.JTextField idtxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JMenuItem logout;
    private javax.swing.JMenuItem menu1;
    private javax.swing.JMenuItem menu2;
    private javax.swing.JMenuItem menu3;
    private javax.swing.JTextField nametxt;
    private javax.swing.JMenu option;
    private javax.swing.JTextField prctxt;
    private javax.swing.JButton process;
    private javax.swing.JTextField qtytxt;
    private javax.swing.JMenuItem refresh;
    private javax.swing.JMenuItem rep1;
    private javax.swing.JMenuItem rep2;
    private javax.swing.JMenuItem rep3;
    private javax.swing.JMenuItem rep4;
    private javax.swing.JButton sellProdReport;
    private javax.swing.JTextField totaltxt;
    // End of variables declaration//GEN-END:variables
}
